from uuid import UUID

type ActorId = UUID
type CandidateFactId = UUID
type CaseId = UUID
type ConfirmedFactId = UUID
type ConflictId = UUID
type DocumentId = UUID
type DocumentVersionId = UUID
type EvidenceId = UUID
type EvidenceGapId = UUID
type FacilityId = UUID
type FactConfirmationId = UUID
type FinancingRequestId = UUID
type HandoffId = UUID
type PolicyCitationId = UUID
type RepaymentEventId = UUID
type TaskId = UUID
type UploadIntentId = UUID
